name: IRC Notification

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  dtirc:
    if: github.repository == 'victoryforce/darktable-commit-notifier'
    runs-on: ubuntu-latest
    concurrency: irc_bot
    steps:
      - uses: actions/checkout@v6
        with:
          repository: 'darktable-org/darktable'
          # We don't need to get all the commits, just more than
          # can realistically be added to the repository between
          # two notifier runs. 100 seems like a reasonable value.
          fetch-depth: 100
          path: src
      - uses: dawidd6/action-download-artifact@v19
        continue-on-error: true
        with:
          workflow: irc.yml
          name: recent_commit
          # We need 'ignore' to bootstrap this workflow. Otherwise
          # we will fail here and will not be able to proceed futher.
          if_no_artifact_found: ignore
      - name: Prepare commit log for IRC
        id: gitlog
        run: |
          cd src;
          # 'recent_commit' contains the commit that was the most recent
          # when this workflow was last run.
          # If this is the first run, we'll limit ourselves to a reasonable
          # number of commits to notify IRC about (10 is good).
          if [ ! -f ../recent_commit ]; then
            git log --format="%H" -n 1 --skip 10 > ../recent_commit
          fi;
          git log --format="%H" -n 1 > ../current_commit
          if cmp -s ../recent_commit ../current_commit; then
            echo "no new commits since last run"
            # An empty log variable will disable the IRC message action,
            # so there will be no empty messages if there are no commits.
            echo "log=" >> $GITHUB_OUTPUT
          else
            git log --reverse --first-parent --pretty=format:"%h: %s (%aN)" `cat ../recent_commit`..`cat ../current_commit` | perl -pe 'if(/pull request #(\d+)/){$title=`curl -s https://api.github.com/repos/darktable-org/darktable/pulls/$1|jq -r .title`;chomp $title;s/pull request/"$title"/}' >> ../log
            echo "current log:"
            cat ../log
            echo "";
            echo "setting output..."
            output="$(cat ../log)"
            echo "log<<EOF"$'\n'"$output"$'\n'EOF >> "$GITHUB_OUTPUT"
            echo ""
            echo "" >> ../log
            echo "llc=$(wc -l < ../log)" >> $GITHUB_OUTPUT
          fi;
          cd ..
          mv -f current_commit recent_commit
      - name: Test print of content to be sent to IRC
        if: ${{ steps.gitlog.outputs.log != '' }}
        run: |
          echo  "${{ steps.gitlog.outputs.log }}" > ../text-to-be-send
          cat ../text-to-be-send
      - name: IRC notification
        if: ${{ steps.gitlog.outputs.log != '' }}
        uses: Gottox/irc-message-action@main
        with:
          server: "irc.oftc.net"
          channel: '#darktable'
          nickname: dt-commit-notifier
          # We want to use a timeout just to avoid interrupting
          # the bot's messages with a bot disconnect notification.
          # We don't actually expect or process any response.
          response_allow_from: victoryforce[m]
          response_timeout: 5
          message: |-
            Showing last ${{ steps.gitlog.outputs.llc }} commit(s) to darktable-org/darktable:
            ${{ steps.gitlog.outputs.log }}
      - uses: actions/upload-artifact@v7
        with:
          name: recent_commit
          path: recent_commit
          if-no-files-found: warn
