name: Keepalive workflow

on:
  schedule:
    - cron: "0 4 11 * *"
  workflow_dispatch:

jobs:
  workflow-keepalive:
    # if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@main
